#!/usr/bin/env /usr/local/bin/bash

. ${BT}/settings

source <( echo "$("${BT}"/cmd/_path -s 2>/dev/null)" )

echo -ne "\n\n----------------------------------\n"
echo -ne     "installing pipx deps...           \n"
echo -ne     "----------------------------------\n\n"

pipx ensurepath

echo -ne "\n\ninstalling pipx packages.\n"

pipx install awsume
pipx inject  awsume awsume-console-plugin
pipx inject  awsume awsume-default-profile-plugin
pipx install aws-sso-util
pipx install aws-whoami 

echo -ne "\n\n--------------------------\n" 
echo -ne     "python packages installed:\n" 
echo -ne     "--------------------------\n\n" 

# NOTE: experimental.
pipx install -f aws-fuzzy-finder

# local installs
#declare -a packages 
#declare -a apps


pipx uninstall devops-sso-util || true
pipx uninstall bin2ools-ssm || true
pipx uninstall bin2ools-rds || true

# install devops and b2 namespace packages.
u="git+https://github.com/analyticsmd"
p="devops-sso-util"
g="@master#subdirectory"
opts="-f --include-deps"

# echo installing the main package: ${CYAN}devops-sso-util${NC}.

pipx install $opts "devops-sso-util @ $u/$p$g=cli&devops-sso-util"

opts="-f --include-apps --include-deps"
pipx inject $opts devops-sso-util "b2rds @ $u/$p$g=b2rds&rds_complete&rds_generate&rds_local&dg&rds_refresh"
pipx inject $opts devops-sso-util "b2ssm @ $u/$p$g=b2ssm&ssm_complete&ssm_generate&ssm_local

pipx list
echo "LAST pipx command!"
pipx completions

