#!/usr/bin/env bash

############################################################################
#                                                                          #
# WARNING: This file is dynamically generated as part of BINTOOLS.         #
#          Changes made here are likely to be overwritten without notice.  # 
#          ----------------------------------------------------------------#
#          To make changes to this document, find the corresponding        #
#          generator script under ${BT}/utils/gen and edit the             # 
#          appropriate sections.                                           #
#                                                                          #
# NOTE:    In a pinch, you can also rename this file by prepending one or  # 
#          more underscores (_) and it will be preserved.                  #
#                                                                          #
############################################################################




complete -W "
  airflowcommonvpc-cluster \
  bmc-amd \
  bsmhealth-amd \
  conehealth-amd \
  demo-a-amd \
  demo-b-amd \
  demo-c-amd \
  demo-d-amd \
  demo-e-amd \
  demo-f-amd \
  dignity-amd \
  dignity-mirthdb-rds \
  emory-amd \
  emory-mirthdb-for-nginx2 \
  fairview \
  fairview-analyticsmd \
  honorhealth-amd \
  kaiser-amd \
  keckmedicine-amd \
  mama-mirth-cluster \
  marshfield-amd \
  medstar2-amd \
  medstar-mirthdb \
  mercynet-amd \
  mercynet-mirth2-bk-db-cluster \
  natividad3-amd \
  natividad3-serverless-rds \
  natividad-mirthdb \
  non-prod-ehr \
  nyp-amd \
  nyp-mirthdb2 \
  nyp-mirthdb-cluster \
  qa-app-01-amd \
  qa-app-02-amd \
  qa-app-03-amd \
  qa-app-04-amd \
  qa-app-05-amd \
  qa-devops-r6g \
  saintlukes-amd \
  sutter-amd \
  sutter-mirthdb-cluster \
  thedacare-amd \
  uams-amd \
  unitypoint-amd \
  uvahealth-amd \
  wellspan-amd \
" rds rds_gui rds_local rds_tunnel rds_connect rds_complete rds_alias

