#!/usr/bin/env /usr/local/bin/bash

BT=${HOME}/.bt
. ${BT}/lib/bt
. ${BT}/src/inst_map.src

autologin 

# ssh connectivity over ssm.
# ---------------------------------------
# Required: Run all generators first.
# This will produce the necessary files 
# for an up-to-date run. 
#
# Generators required
# -------------------
# ssm.gen; 
#
# Generate.d files required
# --------------------------
# ssm.src, ssm.cmpl
#  
host=${1:-NONE}

[[ "$host" == "NONE" ]] && echo "Usage: ssh_over_ssm <host>" && exit 1

# source list of hostnames and instance_ids. 
# Queries aws for a list of all instances.
# Caches them as an associative array in a
# local file in the generate.d dir.
#
#cache_inst

#debug $(declare -p inst_map)
debug echo host: ${inst_map[$host]}

target=$(echo ${inst_map[$host]} | gawk -F, '{print $2}') 

[[ -z "${target}" ]] && \
echo "FATAL: Cannot find host record for: ${host}" \
&& exit 1

echo "starting ssm connection to $host (aka $target) ... "
aws ssm start-session --target ${target}

