#!/usr/bin/env /usr/local/bin/bash

# shellcheck shell=bash disable=SC1083 format=SC1083
BT=${HOME}/.bt
. ${HOME}/.bt/lib/bt
. ${HOME}/src/inst_maps.src

# Test ssm connectivity to a single host.
# ---------------------------------------
# Required: Run the inst generator first.
# This will produce the necessary files 
# for an up-to-date run. 
#
# Generators required
# -------------------
# ssm.gen; 
#
# Generate.d files required
# --------------------------
# ssm.src, ssm.cmpl
#
hn="${1}"
# fully populated inst_map array.
declare -A inst_map
source <(cat "${BT}/src/inst_map.src")
#shopt -s extglob

#BT_DEBUG=yes
[[ -z "${hn}" || "${hn}" == "NONE" ]] && { 
  #export=$(hn="${1}")
  ip=$(aws-fuzzy --ip-only)
  for rec in ${inst_map[@]}; do
    [[ "${rec}" = *$ip* ]] && { 
      export hn="$(echo "${rec}" | cut -d',' -f 1)" 
      export inst="$(echo "${rec}" | cut -d',' -f 2)"
      export ip="$(echo "${rec}" | cut -d',' -f 3)"
      echo "ip: $ip, inst: $inst, hn: $hn"
    }
  done
}
#shopt -o extglob

# shellcheck disable=SC2154A  format=quiet
. bt
#source "${BT}"/lib/cache 
#source "${BT}"/lib/api 

inst="$(echo ${inst_map[$hn]} | cut -d',' -f2)" 
ipt="$(echo ${inst_map[$hn]} | cut -d',' -f3)" 
echo "ip: $ip, inst: $inst, hn: $hn"
[[ -z "${inst}" || -z "${ip}" ]] && \
echo -e "starting ssm connection to: \"${CYAN}${hn}${NC}\""
cmd="aws ssm start-session --target ${inst}"

${cmd}
