#!/usr/bin/env /usr/local/bin/bash

# TODO: Add '-h' menu. 
# TODO: Add 'help' func. 
# TODO: Add virtualenv detector.  
# TODO: Add aliases for rds, ssm, et al. 


~/.local/pipx/venvs/devops-sso-util/lib/python3.10/site-packages/b2rds/

export BT="${HOME}/.bt" 
source ${BT}/settings
[[ "$(type -t bt_init)" == "alias" ]] && bt_init

# add inits
