#!/usr/local/bin/bash

show_spinner()
{
  local -r pid="${1}"
  local -r delay='0.75'
  #local spinstr='\|/-'
  local spinstr="${RED}\\${NC}${YELLOW}|${NC}${BLUE}/${NC}${GREEN}-${NC}"
  local temp
  while ps a | awk '{print $1}' | grep -q "${pid}"; do
    temp="${spinstr#?}"
    printf -e " [%c]  " "${spinstr}"
    spinstr=${temp}${spinstr%"${temp}"}
    sleep "${delay}"
    printf "\b\b\b\b\b\b"
  done
  printf "    \b\b\b\b"
}

("$@") &
show_spinner "$!"
